### ISSUE TITLE
Fix -o help output to cover custom-columns with example

### ISSUE THREAD

**Issue by iawells** [cgascoig/isctl#69]
```
$ isctl get virtualization iwevirtualdisk --select Name,Size --output csv
"Name","Moid","ClassId","ObjectType","Size"
```

(Also, incidentally, it seems like there's no way to get rid of the moid column?)

**Comment by cgascoig** [comment]
`--select X,Y,Z` really just sets `$select=X,Y,Z` on the API query. There are some attributes like Moid, ClassId, and ObjectType that the API always includes so they get included in the output.

To precisely control the columns in table output, you can use `-o custom-columns`:
```
$ isctl get ntp policy -o custom-columns=Name:.Name,Enabled:.Enabled
---------------------------------  ------------
                            Name       Enabled
---------------------------------  ------------
                         NTP_ESL          True
                        CiscoNTP          True
```
or for CSV:
```
$ isctl get ntp policy -o csv=Name:.Name,Enabled:.Enabled
"Name","Enabled"
"NTP_ESL","True"
"CiscoNTP","True"
```

`--select` can still be used with both of those output options but then it is really just reducing the data transferred from the API to client. 

Clearly the commands above are a bit more verbose than your original - perhaps a simplification I can add would be to treat `-o custom-columns=Name,Enabled` the same as `-o custom-columns=Name:.Name,Enabled:.Enabled`. i.e. if the JSONpath expression for a column is missing, assume it should be for an attrribute with the same name as the column title.

**Comment by iawells** [comment]
Commandline help does not document that your alternative exists:

>  -o, --output string     Output format. One of: default, yaml, json, table (default "default")

or really how I should use it (why '.Enabled, what list am I choosing from, .etc.)  I'd certainly appreciate a bit more information on that.
