### ISSUE TITLE
Deprecate --jsonpath and add -o jsonpath with support for kubectl simplified JSONpath syntax

### ISSUE THREAD

**Issue by iawells** [cgascoig/isctl#70]
What I'd like is something like OpenStack's -f raw (see also -f shell for even more inspiration):

```
$ isctl get jobbies --select Name --output raw
thing
wotchamacallit
doodad
```

because this is really useful in shellscripts:

```
for f in $(isctl get jobbies --select Name --output raw); do
    # work on one of my jobbies
done
```

**Comment by cgascoig** [comment]
The --jsonpath option is intended for exactly this use case:

```
for moid in $(isctl get ntp policy --jsonpath '$[*].Moid'); do 
  isctl update ntp policy moid ${moid} --NtpServers 1.1.1.1
done
```

Does that meet you needs? If so, I will change this issue to document this better.

**Comment by iawells** [comment]
I think that documentation would be valuable.

However, the weird thing about this is not so much the jsonpath used to filter (nice trick, btw) but the output format.  You have specified your output formats as default, yaml, json, table (and now CSV), but the format 'default' is what's in use here, and it's unpredictable; it changes the output format based on its own heurstics about what best suits the input.  Sometimes it's a table, sometimes it's not-YAML with a warning that it's not YAML if the table might be a bit big, and in this one case it's what I would call 'raw'.  I can't explicitly say 'give me raw output', it seems that I do that by using a jsonpath to encourage 'default' output to be raw-form.

**Comment by cgascoig** [comment]
Yes, you are absolutely right, --jsonpath was added before the various output options were fleshed out and I had a different mental model for how jsonpath was going to work. 

I have been thinking for a while that it would make much more sense to move it under `-o jsonpath=<expr>` just like the other output modes. This would also be more in line with what kubectl [does](https://kubernetes.io/docs/reference/kubectl/jsonpath/). It would also be a good opportunity to accept the simplified syntax (essentially dropping the $) that kubectl does.
